:doctype: article
:toc: left
:toc-title: Contents
:icons: font
:source-highlighter: rouge
:pygments-style: rouge
:pygments-linenums-mode: inline
:author_name: Patrick Toca
:author_email: patrick.toca@cbre.com
:stylesheet: ./asciidoctor.css
:relfileprefix: ./
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:sectnums:
:sectnumlevels: 1

= migration to asciidoc
{author_name}
v0.0.1, August 9th, 2020: migration to asciidoc

'''

Version: {revnumber}

Version Date: {revdate}

Version Notes: {revremark}

Author: {author_name}

Email: {author_email}

'''

== migration to asciidoc

The tool kramdoc can be used efficiently.

See: https://matthewsetter.com/convert-markdown-to-asciidoc-with-kramdown-asciidoc/[https://matthewsetter.com/convert-markdown-to-asciidoc-with-kramdown-asciidoc/]

=== Let's do the transformation

[source,bash]
----
kramdoc --format=GFM --output=Readme.adoc --wrap=ventilate Readme.md

kramdoc --format=GFM --output=postgis_2.0_cheatsheet.adoc --wrap=ventilate postgis_2.md
----

=== Generating a html document with a ToC

To prepare a generate an html document with its ToC that will be copied to Confluence, run the following command:
[source, bash]
----
asciidoctor -a toc ./README.adoc
----

Or, if you want the ToC on the left handside of the document:
[source, bash]
----
asciidoctor -a toc=left ./README.adoc
----

== Other useful commands

=== migrating html docs to xhtml (useful to publish on Confluence which support xhtml docs only).

Use the tool named `tidy`.

First save the old.adoc document as a html doc. Then transform it in a xhtml one.

[source, bash]
----
tidy -indent -o new.html -asxhtml old.html
----